version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tournament_db
    environment:
      - POSTGRES_DB=tournament
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - ../database/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql:ro
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
